#!/usr/bin/env perl
#A small program that takes input from the user and multiplies it by 5.

use strict;
use warnings;
 
print "What is your number?\n";
# Get the users $number from Standard In
my $number = <STDIN> * 5;
print "Your name is $number\n";

exit
